ganttcharts/web/routes/frontend.py
"""
Routes for the front-end.
"""

import datetime
import functools
import io
import math

import cairocffi
cairocffi.install_as_pycairo()
import cairosvg
import flask
import reportlab.pdfgen.canvas
import reportlab.lib.pagesizes
import reportlab.lib.utils
import PIL.Image
import sqlalchemy

from ganttcharts.chart import Chart, InvalidGanttChart
from ganttcharts.models import Account, AccountEmailAddress, Project, \
    ProjectMember, ProjectResource, ProjectStar
from ganttcharts.web import errors, forms


blueprint = flask.Blueprint('frontend', __name__)


def get_project_or_404(project_id):
    try:
        return flask.g.sql_session.query(Project) \
            .filter(Project.id == project_id).one()
    except sqlalchemy.orm.exc.NoResultFound:
        raise errors.NotFound()


def get_project_member_or_404(member_id):
    return flask.g.sql_session.query(ProjectMember) \
        .filter(ProjectMember.id == member_id).one()


def get_project_resource_or_404(resource_id):
    return flask.g.sql_session.query(ProjectResource) \
        .filter(ProjectResource.id == resource_id).one()


def get_project_member_or_403(project):
    member = project.get_member(flask.g.account)
    if member is None:
        raise errors.NotAuthenticated()
    return member


def login_required(func):
    @functools.wraps(func)
    def decorated_function(*args, **kwargs):
        if 'account' not in flask.g:
            return flask.redirect(flask.url_for('.login',
                                                next=flask.request.url))
        return func(*args, **kwargs)
    return decorated_function


@blueprint.route('/')
def home():
    if 'account' in flask.g:
        return flask.render_template('projects/index.html')
    else:
        return flask.render_template('welcome/index.html')


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = forms.LogIn(flask.request.form)
    if flask.request.method == 'POST' and form.validate():
        account = form.password.record.account
        flask.session['account_id'] = account.id
        if 'next' in flask.request.args:
            return flask.redirect(flask.request.args['next'])
        else:
            return flask.redirect(flask.url_for('.home'))

    return flask.render_template('account/login.html', form=form)


@blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    form = forms.SignUp(flask.request.form)
    if flask.request.method == 'POST' and form.validate():
        account = Account(form.display_name.data, form.email_address.data,
                          form.password.data)
        flask.g.sql_session.add(account)
        flask.g.sql_session.commit()
        return flask.redirect(flask.url_for('.login'))

    return flask.render_template('account/signup.html', form=form)


@blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    del flask.session['account_id']
    return flask.redirect(flask.url_for('.home'))


@blueprint.route('/projects/new', methods=['GET', 'POST'])
@login_required
def new_project():
    form = forms.CreateProject(flask.request.form)
    if flask.request.method == 'POST' and form.validate():
        project = Project(form.name.data, form.description.data,
                          flask.g.account)
        flask.g.sql_session.add(project)
        flask.g.sql_session.commit()
        return flask.redirect(flask.url_for('.view_project',
                                            project_id=project.id))
    return flask.render_template('projects/create.html', form=form)


@blueprint.route('/projects/<int:project_id>')
@login_required
def view_project(project_id):
    project = get_project_or_404(project_id)
    account_member = get_project_member_or_403(project)

    if not account_member.access_level.can_view:
        raise errors.MissingPermission('can_view')

    return flask.render_template('projects/view.html', project=project)


@blueprint.route('/projects/<int:project_id>/gantt-chart.<format>')
def project_gantt_chart(project_id, format):
    project = get_project_or_404(project_id)
    get_project_member_or_403(project)

    try:
        chart = Chart(project)
    except InvalidGanttChart:
        chart = None

    dynamic = format == 'svg'

    svg = flask.render_template('projects/gantt-chart.svg', chart=chart,
                                project=project, dynamic=dynamic,
                                today=datetime.datetime.utcnow())

    if format == 'svg':
        response = flask.make_response(svg)
        response.mimetype = 'image/svg+xml'
    elif format == 'pdf':
        png = cairosvg.svg2png(svg)
        image = PIL.Image.open(io.BytesIO(png))

        page_size = tuple(reversed(reportlab.lib.pagesizes.A4))
        page_margin = 50

        output = io.BytesIO()
        canvas = reportlab.pdfgen.canvas.Canvas(output, pagesize=page_size)

        def draw_title_header():
            x = page_size[0] / 2
            y = page_size[1] - page_margin
            title1 = 'Gantt Chart for {}'.format(project.name)
            title2 = '{} to {}'.format(chart.start.date(), chart.end.date())
            canvas.setFont('Helvetica', 14)
            canvas.drawCentredString(x, y - 10, title1)
            canvas.setFont('Helvetica', 10)
            canvas.drawCentredString(x, y - 25, title2)

        chart_x = page_margin
        chart_y = page_margin
        chart_width = int(page_size[0] - chart_x - page_margin)
        chart_height = int(page_size[1] - chart_y - page_margin - 50)

        new_height = int(chart_height)
        new_width = int(image.width * (new_height / image.height))
        image = image.resize((new_width, new_height), PIL.Image.ANTIALIAS)

        def split_image():
            for i in range(math.ceil(image.width / chart_width)):
                x2 = (i + 1) * chart_width
                if x2 >= image.width:
                    box = (i * chart_width, 0, image.width, image.height)

                    final = PIL.Image.new(mode='RGB',
                                          size=(chart_width, chart_height),
                                          color=(255, 255, 255))
                    final.paste(image.crop(box), (0, 0))
                    yield final
                else:
                    box = (i * chart_width, 0, x2, image.height)
                    yield image.crop(box)

        for subimage in split_image():
            canvas.drawImage(reportlab.lib.utils.ImageReader(subimage),
                             chart_x, chart_y, width=chart_width,
                             height=chart_height)
            draw_title_header()
            canvas.showPage()

        canvas.save()

        pdf = output.getvalue()
        output.close()

        response = flask.make_response(pdf)
        response.mimetype = 'application/pdf'
    elif format == 'png':
        png = cairosvg.svg2png(svg)

        response = flask.make_response(png)
        response.mimetype = 'image/png'
    else:
        raise errors.NotFound()

    if format != 'svg':
        if not flask.current_app.debug:
            filename = 'Gantt Chart for {}.{}'.format(project.name, format)
            content_disposition = 'attachment; filename="{}"'.format(filename)
            response.headers['Content-Disposition'] = content_disposition

    return response


@blueprint.route('/projects/<int:project_id>/star')
@login_required
def star_project(project_id):
    # TODO check if they are a member
    star = ProjectStar(account=flask.g.account, project_id=project_id)
    flask.g.sql_session.add(star)
    flask.g.sql_session.commit()
    return flask.redirect(flask.url_for('.home'))


@blueprint.route('/projects/<int:project_id>/unstar')
@login_required
def unstar_project(project_id):
    star = flask.g.sql_session.query(ProjectStar) \
        .filter(ProjectStar.account == flask.g.account) \
        .filter(ProjectStar.project_id == project_id) \
        .one()
    flask.g.sql_session.delete(star)
    flask.g.sql_session.commit()
    return flask.redirect(flask.url_for('.home'))


@blueprint.route('/account')
@login_required
def account():
    return flask.render_template('account/index.html')


@blueprint.route('/account/email-addresses', methods=['POST'])
@login_required
def account_email_addresses():
    form = forms.EmailAddress(flask.request.form)
    if form.validate():
        email_address = AccountEmailAddress(form.email_address.data)
        flask.g.account.email_addresses.append(email_address)
        flask.g.sql_session.commit()
    else:
        flask.flash('Could not add email address.', 'warning')
    return flask.redirect(flask.url_for('.account'))


@blueprint.route('/account/reset', methods=['GET', 'POST'])
@blueprint.route('/account/reset/<int:account_id>'
                 '/<reset_password_key>', methods=['GET', 'POST'])
def account_reset(account_id=None, reset_password_key=None):
    if account_id is not None and reset_password_key is not None:
        account = flask.g.sql_session.query(Account) \
            .filter(Account.id == account_id) \
            .filter(Account.reset_password_key == reset_password_key) \
            .filter(Account.reset_password_key_expiration_date >= datetime.datetime.now()) \
            .one()

        form = forms.AccountReset2(flask.request.form)
        if flask.request.method == 'POST' and form.validate():
            account.password = form.new_password.data
            account.reset_password_key = None
            account.reset_password_key_expiration_date = None
            flask.g.sql_session.commit()

            flask.flash('Your password has been changed.', 'success')
            return flask.redirect(flask.url_for('.login'))

        return flask.render_template('account/reset.html', stage=2, form=form)
    else:
        form = forms.AccountReset1(flask.request.form)
        if flask.request.method == 'POST' and form.validate():
            account = form.email_address.record.account

ganttcharts/web/templates/_includes/ad.html
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Gantt Charts -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3110873768240114"
     data-ad-slot="4328647982"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

ganttcharts/web/templates/_includes/analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71084978-5', 'auto');
  ga('send', 'pageview');
</script>

ganttcharts/web/templates/_includes/page.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

    <meta name="theme-color" content="rgb(255, 228, 124)" />
    <meta name="mobile-web-app-capable" content="yes" />

    {% block meta %}
    {% endblock %}

    <title>{% block title %}Gantt Charts{% endblock %}</title>

    <link href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='bower_components/ionicons/css/ionicons.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='styles/theme.css') }}" rel="stylesheet" />

    <link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}" />
    <link rel="icon" sizes="192x192" href="{{ url_for('static', filename='images/icon-192.png') }}" />
    <link rel="apple-touch-icon" sizes="128x128" href="{{ url_for('static', filename='images/icon-128.png') }}" />

    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}" />

    <script src="{{ url_for('static', filename='bower_components/webcomponentsjs/webcomponents-lite.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/requests.js') }}"></script>

    {% block imports %}
    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <a class="navbar-brand" href="{{ url_for('frontend.home') }}">Gantt Charts &nbsp;<span class="ion-ios-home"></span></a>

      {% if g.account %}
        <ul class="nav navbar-nav">
          {% for star in g.account.stars %}
            <li class="nav-item {% if current_project == star.project.id %}active{% endif %}">
              <a class="nav-link" href="{{ url_for('frontend.view_project', project_id=star.project.id) }}">{{ star.project.name }}</a>
            </li>
          {% endfor %}
        </ul>

        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item {% if section == 'account' %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('frontend.account') }}">My Account</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('frontend.logout') }}">Log out</a>
          </li>
        </ul>
      {% else %}
        <form class="form-inline navbar-form pull-xs-right hidden-sm-down" action="{{ url_for('frontend.login') }}" method="POST">
          <div class="form-group">
            <input type="email" name="email_address" placeholder="Email address" class="form-control">
          </div>
          <div class="form-group">
            <input type="password" name="password" placeholder="Password" class="form-control">
          </div>
          <button type="submit" class="btn btn-success">Log in</button>
        </form>

        <ul class="nav navbar-nav pull-xs-right hidden-md-up">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('frontend.login') }}">Log in</a>
          </li>
        </ul>
      {% endif %}
    </nav>

    {% block body %}
      <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endwith %}

        <div class="page">
          {% block page %}
          {% endblock %}
        </div>
      </div>
    {% endblock %}

    <footer class="footer m-t-3">
      <div class="container m-b-2">
        {% include "_includes/ad.html" %}
      </div>

      <div class="container">
        <div class="text-xs-center m-b m-t-2">
          <img class="orycion" src="{{ url_for('static', filename='images/orycion.png') }}" width="72" height="72" />
        </div>

        <p class="text-xs-center text-muted">
          A website by <a href="https://www.thomasleese.me">Thomas Leese</a> and <a href="https://uk.linkedin.com/in/vikashtank">Vikash Tank</a>.
        </p>

        <p class="text-xs-center text-muted">
          <small><a href="mailto:feedback@ganttcharts.xyz">Submit Feedback</a> &middot; <a href="https://github.com/thomasleese/gantt-charts">Code</a></small>
        </p>
      </div>
    </footer>

    <script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>

    {% block scripts %}
    {% endblock %}

    {% include "_includes/analytics.html" %}
  </body>

</html>